<?php 
/**
 * WT Slideshow Manager for Zen Cart.
 * WARNING: Do not change this file. Your changes will be lost.
 *
 * @copyright 2021 WT Tech. Designs.
 * Version : WT Slideshow Manager 1.0
 */

$db->Execute("UPDATE " . TABLE_CONFIGURATION . " SET configuration_value = '1.0.1' WHERE configuration_key = 'WT_SLIDESHOW_MANAGER_VERSION' LIMIT 1;");

$db->Execute("
INSERT IGNORE INTO ".TABLE_WT_SLIDESHOW_MANAGER." (wtsm_id, wtsm_title, wtsm_full_screen, wtsm_width, wtsm_height, wtsm_infinite, wtsm_on_hover, wtsm_controls, wtsm_pager, wtsm_autoplay, wtsm_interval_time, wtsm_slide_speed, wtsm_slide_animation, wtsm_slider_background_color, wtsm_date_added, wtsm_updated_at, wtsm_status) VALUES
(1, 'Home - 1', 0, '0', '0', 1, 0, 1, 1, 0, '10000', 300, 'fade', '#ffc156', '2021-08-05 14:01:18', '2023-02-09 10:30:13', 1),
(3, 'Home - 2', 0, '0', '0', 1, 0, 1, 1, 1, '3000', 300, 'fade', NULL, '2021-08-15 10:40:08', '2023-01-27 08:22:16', 1);
");

$db->Execute("
INSERT IGNORE INTO ".TABLE_WT_SLIDESHOW_MANAGER_BANNERS." (wtsmb_id, wtsm_id, wtsmb_title, wtsmb_type, wtsmb_background_color, wtsmb_background_image, wtsmb_cp, wtsmb_cptop, wtsmb_cpleft, wtsmb_url, wtsmb_image, wtsmb_extra_classes, wtsmb_item_image, wtsmb_sort_order, wtsmb_expires_impressions, wtsmb_date_scheduled, wtsmb_expires_date, wtsmb_date_added, wtsmb_date_status_change, wtsmb_updated_at, wtsmb_status) VALUES
(1, 1, 'Banner - 1', 'ban_img_with_content', '#ffc156', NULL, 'cp-custom', 20, 5, '', 'wtsm_images/hm1-slide1.png', 'px-4', '', 1, 0, '2021-08-09 00:00:00', '2031-08-25 23:59:59', '2021-08-05 14:02:43', '0001-01-01 00:00:00', '2023-02-07 14:01:03', 1),
(2, 1, 'Banner - 2', 'ban_img_with_content', '#ffc156', NULL, 'cp-custom', 20, 5, '', 'wtsm_images/hm1-slide1.png', 'px-4', '', 2, 0, '2021-09-08 00:00:00', '2031-08-25 23:59:59', '2021-08-05 14:03:16', '2021-08-11 12:40:39', '2023-02-07 12:25:34', 1),
(4, 3, 'Banner - 1', 'ban_img_with_content', '', 'wtsm_images/hm2-s1-b1.jpg', 'cp-center', 0, 0, '', '', 'd-flex align-items-center', '', 1, NULL, '2021-08-09 00:00:00', '2031-08-25 23:59:59', '2021-08-15 10:41:23', '0001-01-01 00:00:00', '2023-02-06 07:38:15', 1),
(5, 3, 'Banner - 2', 'ban_img_with_content', '', 'wtsm_images/hm2-s1-b1.jpg', 'cp-center', 0, 0, '', '', 'd-flex align-items-center', '', 2, 0, '2021-08-09 00:00:00', '2031-08-25 23:59:59', '2021-08-15 10:44:16', '2023-02-03 11:19:32', '2023-02-06 07:42:42', 1);
");

$db->Execute("
INSERT IGNORE INTO ".TABLE_WT_SLIDESHOW_MANAGER_BANNERS_CONTENT." (wtsmbc_id, wtsmb_id, languages_id, wtsmbc_content) VALUES
(1, 1, 1, '&lt;div class=&quot;slider_content&quot;&gt;\r\n	&lt;h4 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.4s&quot;&gt;sell to get what you love&lt;/h4&gt;\r\n	&lt;h3 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.6s&quot;&gt;The Gift you are Wishing&lt;/h3&gt;\r\n	&lt;div class=&quot;item_price&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;.8s&quot;&gt;\r\n		&lt;small&gt;From&lt;/small&gt;\r\n		&lt;sup&gt;£&lt;/sup&gt;749&lt;sup&gt;99&lt;/sup&gt;\r\n	&lt;/div&gt;\r\n	&lt;div class=&quot;abtn_wrap clearfix&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;1s&quot;&gt;\r\n		&lt;a href=&quot;#!&quot; class=&quot;custom_btn btn_round bg_supermarket_red&quot;&gt;Start Buying&lt;/a&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(5, 2, 1, '&lt;div class=&quot;slider_content&quot;&gt;\r\n	&lt;h4 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.4s&quot;&gt;sell to get what you love&lt;/h4&gt;\r\n	&lt;h3 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.6s&quot;&gt;The Gift you are Wishing&lt;/h3&gt;\r\n	&lt;div class=&quot;item_price&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;.8s&quot;&gt;\r\n		&lt;small&gt;From&lt;/small&gt;\r\n		&lt;sup&gt;£&lt;/sup&gt;749&lt;sup&gt;99&lt;/sup&gt;\r\n	&lt;/div&gt;\r\n	&lt;div class=&quot;abtn_wrap clearfix&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;1s&quot;&gt;\r\n		&lt;a href=&quot;#!&quot; class=&quot;custom_btn btn_round bg_supermarket_red&quot;&gt;Start Buying&lt;/a&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(9, 3, 1, '&lt;div class=&quot;item_content&quot;&gt;\r\n	&lt;span class=&quot;item_price&quot;&gt;£99.00&lt;/span&gt;\r\n	&lt;h4 class=&quot;sub_title text-white&quot;&gt;ALL-NEW-SPORT&lt;/h4&gt;\r\n	&lt;h3 class=&quot;item_title text-white mb_30&quot;&gt;\r\n		Everything you need to Start an online store \r\n	&lt;/h3&gt;\r\n	&lt;a class=&quot;custom_btn btn_round bg_electronic_blue&quot; href=&quot;#!&quot;&gt;Start Buying&lt;/a&gt;\r\n&lt;/div&gt;'),
(13, 4, 1, '&lt;div class=&quot;container&quot;&gt;\r\n	&lt;div class=&quot;slider_content&quot;&gt;\r\n		&lt;h3 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.6s&quot;&gt;Sweet Home Collection.&lt;/h3&gt;\r\n		&lt;p data-animation=&quot;fadeInUp&quot; data-delay=&quot;.8s&quot;&gt;\r\n			Discover new ways to dress this spring with a selection of the best designer jackets.\r\n		&lt;/p&gt;\r\n		&lt;div class=&quot;abtn_wrap clearfix&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;1s&quot;&gt;\r\n			&lt;a href=&quot;#!&quot; class=&quot;custom_btn bg_white text-uppercase&quot;&gt;Collection&lt;/a&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(17, 5, 1, '&lt;div class=&quot;container&quot;&gt;\r\n	&lt;div class=&quot;slider_content&quot;&gt;\r\n		&lt;h3 data-animation=&quot;fadeInUp&quot; data-delay=&quot;.6s&quot;&gt;Sweet Home Collection.&lt;/h3&gt;\r\n		&lt;p data-animation=&quot;fadeInUp&quot; data-delay=&quot;.8s&quot;&gt;\r\n			Discover new ways to dress this spring with a selection of the best designer jackets.\r\n		&lt;/p&gt;\r\n		&lt;div class=&quot;abtn_wrap clearfix&quot; data-animation=&quot;fadeInUp&quot; data-delay=&quot;1s&quot;&gt;\r\n			&lt;a href=&quot;#!&quot; class=&quot;custom_btn bg_white text-uppercase&quot;&gt;Collection&lt;/a&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(21, 6, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInRight&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(25, 7, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2&quot;&gt;Use Unique&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(29, 8, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Oberlo&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Find Products for&lt;br&gt;Shop Store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;Oberlo allows you to easily import dropshipped products directly into your ecommerce store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(33, 9, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Ready To&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(37, 10, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(41, 11, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Use Unique&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4 &quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(45, 12, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(49, 13, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Oberlo&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Find Products for&lt;br&gt;Shop Store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;Oberlo allows you to easily import dropshipped products directly into your ecommerce store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(53, 14, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1&quot;&gt;&lt;span class=&quot;tt-base-color&quot;&gt;Multipurpose&lt;/span&gt;&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(57, 15, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Use Unique&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(61, 16, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Use Unique&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-dark btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(65, 17, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(69, 18, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(73, 19, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInLeft&quot;&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-1 tt-white-color&quot;&gt;Ready To&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-2 tt-white-color&quot;&gt;Use Unique&lt;br&gt;Demos&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-3&quot;&gt;Optimized for speed, website that sells&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(77, 20, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInRight&quot;&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-1 tt-white-color&quot;&gt;&lt;span class=&quot;tt-base-color&quot;&gt;Multipurpose&lt;/span&gt;&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-2 tt-white-color&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-3 tt-white-color&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(81, 21, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-1 tt-base-color&quot;&gt;&lt;span class=&quot;tt-base-color&quot;&gt;Oberlo&lt;/span&gt;&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-2 tt-white-color&quot;&gt;Find Products for&lt;br&gt;Shop Store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-3 tt-white-color&quot;&gt;Oberlo allows you to easily import dropshipped products directly into your ecommerce store&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption2-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(85, 22, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-base-color&quot;&gt;Multipurpose&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;Premium&lt;br&gt;Html Template&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;30 skins, powerful features, great support, exclusive offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(89, 23, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-1 tt-white-color&quot;&gt;FALL-WINTER&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-2 tt-white-color&quot;&gt;CLEARANCE&lt;br&gt;SALES&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-3 tt-white-color&quot;&gt;All Sale Items are Final Sale / Free Shipping on All Orders&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;btn btn-xl&quot; data-text=&quot;SHOP NOW!&quot;&gt;SHOP NOW!&lt;/a&gt;&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;'),
(93, 24, 1, '&lt;div class=&quot;wtslider-text-content slider-revolution txt-middle&quot;&gt;\r\n	&lt;div class=&quot;wtslider-text-content-flex container&quot;&gt;\r\n		&lt;div class=&quot;wtslider-vert w-60 mx-0 tp-caption1&quot;&gt;\r\n			&lt;div class=&quot;wtslider-text text-center&quot; data-animation=&quot;fadeInUp&quot;&gt;\r\n				&lt;div class=&quot;tp-caption3-wd-1&quot;&gt;Special Offer&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption3-wd-2&quot;&gt;Final Clearance&lt;br&gt; Up to 80% Off&lt;/div&gt;\r\n				&lt;div class=&quot;tp-caption1-wd-4 tp-caption-list-btn&quot;&gt;\r\n					&lt;a href=&quot;#&quot; target=&quot;_blank&quot; class=&quot;btn btn-xl btn-white&quot; data-text=&quot;SHOP WOMEN&quot;&gt;SHOP WOMEN&lt;/a&gt;&lt;a href=&quot;#&quot; target=&quot;_blank&quot; class=&quot;btn btn-xl btn-white&quot; data-text=&quot;SHOP MEN&quot;&gt;SHOP MEN&lt;/a&gt;\r\n				&lt;/div&gt;\r\n			&lt;/div&gt;\r\n		&lt;/div&gt;\r\n	&lt;/div&gt;\r\n&lt;/div&gt;');
");